'use strict';

var Actions = {
    CREATE_STUDENT: 'CREATE_STUDENT',
    CREATE_ADMIN: 'CREATE_ADMIN',
    CREATE_DIRECTOR: 'CREATE_DIRECTOR',
    CREATE_GRADE: 'CREATE_GRADE',
    CREATE_SCHOOL: 'CREATE_SCHOOL',
    CREATE_CLASSROOM:'CREATE_CLASSROOM'
};

module.exports = Actions;

